import React, { useState, useEffect } from 'react';
import {
  Copy,
  Check,
  Upload,
  FileCheck,
  AlertTriangle,
  Lock,
  Unlock,
  Calendar,
  User,
  ShieldCheck,
  HardDrive,
  ExternalLink,
  Sparkles,
  Info,
  FileText,
  X,
  Eye,
  CheckCircle2,
  Bot,
  Loader2,
  AlertCircle,
} from 'lucide-react';
import {
  DOCUMENT_TYPES,
  DIVISIONS,
  APPROVERS,
  ROMAN_MONTHS,
  DocumentRecord,
  DocumentStatus,
  CodeDefinition,
} from '../types';
import {
  generateDocumentCode,
  getNextSequenceNumber,
  isCodeDuplicate,
  validateDocumentCode,
  formatSequence,
  getRomanMonth,
} from '../utils/numbering';
import { GoogleDriveSettings } from '../services/storage';
import { uploadFileToDriveViaBot, TARGET_FOLDER_URL } from '../services/googleDriveBot';

interface DocumentGeneratorProps {
  documents: DocumentRecord[];
  onSaveDocument: (doc: DocumentRecord) => Promise<void>;
  driveSettings: GoogleDriveSettings;
  onNavigateToDocuments: () => void;
  onOpenDriveSettings?: () => void;
  documentTypes?: CodeDefinition[];
  divisions?: CodeDefinition[];
  approvers?: CodeDefinition[];
  onNavigateToMasterCategories?: () => void;
}

export const DocumentGenerator: React.FC<DocumentGeneratorProps> = ({
  documents,
  onSaveDocument,
  driveSettings,
  onNavigateToDocuments,
  onOpenDriveSettings,
  documentTypes,
  divisions,
  approvers,
  onNavigateToMasterCategories,
}) => {
  const docTypes = documentTypes && documentTypes.length > 0 ? documentTypes : DOCUMENT_TYPES;
  const divs = divisions && divisions.length > 0 ? divisions : DIVISIONS;
  const apprvs = approvers && approvers.length > 0 ? approvers : APPROVERS;

  // Step selections
  const [selectedType, setSelectedType] = useState<string>(docTypes[0]?.code || 'SOP');
  const [selectedDivision, setSelectedDivision] = useState<string>(divs[0]?.code || 'GNR');
  const [selectedApprover, setSelectedApprover] = useState<string>(apprvs[0]?.code || 'CEO');

  // Date selections
  const currentDate = new Date();
  const [issueDate, setIssueDate] = useState<string>(
    currentDate.toISOString().slice(0, 10)
  );
  const [monthNumber, setMonthNumber] = useState<number>(currentDate.getMonth() + 1);
  const [year, setYear] = useState<number>(currentDate.getFullYear());

  // Manual / Backdating Override Mode
  const [isManualOverride, setIsManualOverride] = useState<boolean>(false);
  const [manualCode, setManualCode] = useState<string>('');
  const [customSequence, setCustomSequence] = useState<number | ''>('');
  const [legacyNotes, setLegacyNotes] = useState<string>('');

  // Metadata
  const [title, setTitle] = useState<string>('');
  const [description, setDescription] = useState<string>('');
  const [createdBy, setCreatedBy] = useState<string>('');
  const [approvedBy, setApprovedBy] = useState<string>('President Director (CEO)');
  const [verifiedBy, setVerifiedBy] = useState<string>('Management Representative (MR)');
  const [status, setStatus] = useState<DocumentStatus>('Published');
  const [revision, setRevision] = useState<number>(0);

  // File Upload & Google Drive
  const [uploadedFile, setUploadedFile] = useState<{
    name: string;
    size: number;
    type: string;
    dataUrl?: string;
  } | null>(null);
  const [googleDriveLink, setGoogleDriveLink] = useState<string>('');

  // UI States
  const [copied, setCopied] = useState<boolean>(false);
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);
  const [savedSuccessDoc, setSavedSuccessDoc] = useState<DocumentRecord | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // Auto-update sequence number when document type changes
  const autoSequence = getNextSequenceNumber(documents, selectedType);
  const effectiveSequence =
    isManualOverride && customSequence !== '' ? Number(customSequence) : autoSequence;

  // Auto-calculated code
  const autoGeneratedCode = generateDocumentCode(
    effectiveSequence,
    selectedType,
    selectedDivision,
    selectedApprover,
    monthNumber,
    year
  );

  // The active code being used
  const activeCode = isManualOverride && manualCode.trim() ? manualCode.trim().toUpperCase() : autoGeneratedCode;

  // Check 1 code 1 document uniqueness rule
  const duplicate = isCodeDuplicate(activeCode, documents);
  const conflictingDoc = duplicate
    ? documents.find((d) => d.code.toUpperCase() === activeCode.toUpperCase())
    : null;

  // Update approver title when approver code changes
  useEffect(() => {
    const approverObj = apprvs.find((a) => a.code === selectedApprover);
    if (approverObj) {
      setApprovedBy(approverObj.label);
    }
  }, [selectedApprover, apprvs]);

  // Sync date changes with month and year
  const handleDateChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newDateStr = e.target.value;
    setIssueDate(newDateStr);
    if (newDateStr) {
      const d = new Date(newDateStr);
      if (!isNaN(d.getTime())) {
        setMonthNumber(d.getMonth() + 1);
        setYear(d.getFullYear());
      }
    }
  };

  // Copy code to clipboard
  const handleCopyCode = async () => {
    try {
      await navigator.clipboard.writeText(activeCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  // Bot Upload State
  const [isBotUploading, setIsBotUploading] = useState<boolean>(false);
  const [botUploadSuccess, setBotUploadSuccess] = useState<{
    viewUrl: string;
    fileName: string;
  } | null>(null);
  const [botUploadError, setBotUploadError] = useState<string | null>(null);

  // File Upload Handler
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setBotUploadSuccess(null);
      setBotUploadError(null);
      const reader = new FileReader();
      reader.onload = () => {
        setUploadedFile({
          name: file.name,
          size: file.size,
          type: file.type,
          dataUrl: reader.result as string,
        });
      };
      reader.readAsDataURL(file);
    }
  };

  // Bot Upload Handler to Target Google Drive
  const handleUploadViaBot = async () => {
    if (!uploadedFile || !uploadedFile.dataUrl) {
      setBotUploadError('Pilih file dokumen terlebih dahulu sebelum mengunggah via Bot.');
      return;
    }

    if (!driveSettings.botWebhookUrl) {
      if (onOpenDriveSettings) {
        onOpenDriveSettings();
      } else {
        alert(
          'URL Webhook Bot Google Apps Script belum disetel. Silakan buka Pengaturan Google Drive untuk memasang script bot.'
        );
      }
      return;
    }

    setIsBotUploading(true);
    setBotUploadError(null);
    try {
      const result = await uploadFileToDriveViaBot(
        uploadedFile.dataUrl,
        uploadedFile.name,
        uploadedFile.type,
        driveSettings.botWebhookUrl,
        {
          documentCode: activeCode,
          uploadedBy: createdBy.trim() || 'Staff NBE',
        }
      );

      if (result.success && result.viewUrl) {
        setGoogleDriveLink(result.viewUrl);
        setBotUploadSuccess({
          viewUrl: result.viewUrl,
          fileName: uploadedFile.name,
        });
      } else {
        setBotUploadError(result.error || 'Bot Google Drive gagal memproses unggahan file.');
      }
    } catch (err: any) {
      setBotUploadError(`Koneksi bot bermasalah: ${err.message}`);
    } finally {
      setIsBotUploading(false);
    }
  };

  // Toggle manual override
  const handleToggleManual = () => {
    if (!isManualOverride) {
      setIsManualOverride(true);
      setManualCode(autoGeneratedCode);
      setCustomSequence(autoSequence);
    } else {
      setIsManualOverride(false);
      setManualCode('');
      setCustomSequence('');
    }
  };

  // Submit and save document
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg(null);

    if (!title.trim()) {
      setErrorMsg('Judul Dokumen wajib diisi.');
      return;
    }

    if (!createdBy.trim()) {
      setErrorMsg('Nama Pembuat Dokumen (Created By) wajib diisi.');
      return;
    }

    // Strict 1 Kode 1 Dokumen check
    if (duplicate) {
      setErrorMsg(
        `Kode "${activeCode}" sudah digunakan untuk dokumen "${conflictingDoc?.title}". 1 kode dokumen hanya boleh berlaku untuk 1 dokumen saja.`
      );
      return;
    }

    // Validate format if manual code
    if (isManualOverride && manualCode) {
      const validation = validateDocumentCode(manualCode);
      if (!validation.isValid) {
        setErrorMsg(validation.message || 'Format kode dokumen tidak valid.');
        return;
      }
    }

    setIsSubmitting(true);
    try {
      const romanMonth = getRomanMonth(monthNumber);
      const newDoc: DocumentRecord = {
        id: `doc-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
        code: activeCode,
        seqNumber: effectiveSequence,
        typeCode: selectedType,
        divisionCode: selectedDivision,
        approverCode: selectedApprover,
        monthRoman: romanMonth,
        year: year,
        title: title.trim(),
        description: description.trim() || undefined,
        revision: revision,
        status: status,
        createdBy: createdBy.trim(),
        approvedBy: approvedBy.trim() || undefined,
        verifiedBy: verifiedBy.trim() || undefined,
        issueDate: issueDate,
        fileName: uploadedFile?.name,
        fileSize: uploadedFile?.size,
        fileType: uploadedFile?.type,
        fileData: uploadedFile?.dataUrl,
        googleDriveLink: googleDriveLink.trim() || undefined,
        isManualCode: isManualOverride,
        legacyNotes: legacyNotes.trim() || undefined,
        revisions: [
          {
            revision: revision,
            date: new Date(issueDate).toLocaleDateString('id-ID', {
              day: 'numeric',
              month: 'short',
              year: 'numeric',
            }),
            description: revision === 0 ? 'Initial Issue' : 'Penerbitan Baru',
            revisedBy: createdBy.trim(),
          },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      await onSaveDocument(newDoc);
      setSavedSuccessDoc(newDoc);

      // Reset form partially
      setTitle('');
      setDescription('');
      setUploadedFile(null);
      setGoogleDriveLink('');
      if (isManualOverride) {
        setIsManualOverride(false);
        setManualCode('');
      }
    } catch (err: any) {
      setErrorMsg(err.message || 'Gagal menyimpan dokumen.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="container" style={{ paddingBottom: '3rem' }}>
      {/* Success Notification Modal / Banner */}
      {savedSuccessDoc && (
        <div
          className="glass-card animate-fade-in"
          style={{
            margin: '1.5rem 0',
            padding: '1.75rem',
            border: '1px solid rgba(16, 185, 129, 0.4)',
            background: 'rgba(16, 185, 129, 0.08)',
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'flex-start',
              justifyContent: 'space-between',
              gap: '1rem',
              flexWrap: 'wrap',
            }}
          >
            <div style={{ display: 'flex', gap: '1rem' }}>
              <div
                style={{
                  background: 'var(--success)',
                  color: '#fff',
                  borderRadius: '50%',
                  width: '42px',
                  height: '42px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  flexShrink: 0,
                }}
              >
                <CheckCircle2 size={24} />
              </div>
              <div>
                <h3 style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--success)' }}>
                  Dokumen Berhasil Didaftarkan & Disimpan!
                </h3>
                <p style={{ marginTop: '0.25rem', color: 'var(--text-main)', fontSize: '0.95rem' }}>
                  Kode Dokumen:{' '}
                  <span
                    className="mono"
                    style={{
                      fontWeight: 700,
                      background: 'rgba(0,0,0,0.3)',
                      padding: '0.2rem 0.6rem',
                      borderRadius: '4px',
                      color: 'var(--primary)',
                    }}
                  >
                    {savedSuccessDoc.code}
                  </span>
                </p>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginTop: '0.35rem' }}>
                  Judul: <strong>{savedSuccessDoc.title}</strong> | Dibuat oleh:{' '}
                  {savedSuccessDoc.createdBy}
                </p>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
              <button
                onClick={onNavigateToDocuments}
                className="btn btn-primary btn-sm"
              >
                Lihat di Database Dokumen
              </button>
              <button
                onClick={() => setSavedSuccessDoc(null)}
                className="btn btn-secondary btn-sm"
              >
                Buat Dokumen Lainnya
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Intro Header */}
      <div style={{ margin: '1.75rem 0 1.25rem 0' }}>
        <h1
          style={{
            fontSize: '1.85rem',
            fontWeight: 800,
            letterSpacing: '-0.03em',
            display: 'flex',
            alignItems: 'center',
            gap: '0.65rem',
          }}
        >
          <Sparkles color="var(--primary)" size={26} />
          Generator & Penomoran Dokumen Otomatis
        </h1>
        <p style={{ color: 'var(--text-secondary)', marginTop: '0.25rem', fontSize: '0.95rem' }}>
          Format standar penomoran dokumen PT Nirwana Bhumi Energi:{' '}
          <span className="mono" style={{ color: 'var(--primary)', fontWeight: 600 }}>
            0000-XXX-YYY-OOO-IX-2026
          </span>
          . Pilih parameter di bawah untuk menghasilkan kode resmi.
        </p>
      </div>

      {/* Live Generated Code Display Hero */}
      <div
        className="glass-card glow-animation"
        style={{
          padding: '1.75rem',
          marginBottom: '2rem',
          border: duplicate
            ? '2px solid var(--danger)'
            : '1px solid var(--border-accent)',
          background: duplicate
            ? 'rgba(239, 68, 68, 0.08)'
            : 'linear-gradient(135deg, rgba(22, 34, 60, 0.9) 0%, rgba(10, 20, 38, 0.95) 100%)',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            flexWrap: 'wrap',
            gap: '1rem',
          }}
        >
          <div>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem',
                marginBottom: '0.5rem',
              }}
            >
              <span
                style={{
                  fontSize: '0.75rem',
                  fontWeight: 700,
                  textTransform: 'uppercase',
                  letterSpacing: '0.08em',
                  color: 'var(--primary)',
                }}
              >
                Kode Dokumen Resmi Tergenerate
              </span>
              {isManualOverride ? (
                <span className="badge badge-warning">
                  <Unlock size={12} />
                  Mode Edit Manual Aktif
                </span>
              ) : (
                <span className="badge badge-primary">
                  <Lock size={12} />
                  Auto-Sequence Standar
                </span>
              )}
            </div>

            {/* The Main Code */}
            <div
              className="mono"
              style={{
                fontSize: 'clamp(1.5rem, 3.5vw, 2.4rem)',
                fontWeight: 800,
                letterSpacing: '0.04em',
                color: duplicate ? 'var(--danger)' : '#ffffff',
                textShadow: duplicate ? 'none' : '0 2px 10px rgba(0, 212, 178, 0.4)',
                wordBreak: 'break-all',
              }}
            >
              {activeCode}
            </div>

            {/* Code Breakdown Explanation */}
            <div
              style={{
                display: 'flex',
                flexWrap: 'wrap',
                gap: '0.4rem',
                marginTop: '0.75rem',
              }}
            >
              <span className="badge badge-blue">
                No. Urut: {formatSequence(effectiveSequence)}
              </span>
              <span className="badge badge-purple">Tipe: {selectedType}</span>
              <span className="badge badge-primary">Divisi: {selectedDivision}</span>
              <span className="badge badge-warning">Penyetuju: {selectedApprover}</span>
              <span className="badge badge-blue">Bulan: {getRomanMonth(monthNumber)}</span>
              <span className="badge badge-purple">Tahun: {year}</span>
            </div>
          </div>

          {/* Action Buttons: Copy & Toggle Manual Edit */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.65rem' }}>
            <button
              type="button"
              onClick={handleCopyCode}
              className="btn btn-primary btn-lg"
              style={{ minWidth: '170px' }}
              title="Salin kode ini ke clipboard"
            >
              {copied ? <Check size={18} /> : <Copy size={18} />}
              <span>{copied ? 'Tersalin!' : 'Copy Kode'}</span>
            </button>

            <button
              type="button"
              onClick={handleToggleManual}
              className="btn btn-secondary btn-sm"
              title="Ubah kode dokumen secara bebas (misal untuk upload dokumen lama)"
            >
              {isManualOverride ? <Lock size={14} /> : <Unlock size={14} />}
              <span>{isManualOverride ? 'Kunci Kembali ke Auto' : 'Ubah Kode Manual'}</span>
            </button>
          </div>
        </div>

        {/* Duplicate Warning Alert Banner (1 KODE 1 DOKUMEN RULE) */}
        {duplicate && (
          <div
            style={{
              marginTop: '1.25rem',
              padding: '0.9rem 1.15rem',
              borderRadius: 'var(--radius-md)',
              background: 'rgba(239, 68, 68, 0.15)',
              border: '1px solid var(--danger)',
              display: 'flex',
              alignItems: 'center',
              gap: '0.75rem',
              color: '#fca5a5',
            }}
          >
            <AlertTriangle size={22} color="var(--danger)" style={{ flexShrink: 0 }} />
            <div style={{ fontSize: '0.875rem' }}>
              <strong style={{ color: '#fff' }}>
                PERINGATAN: KODE DOKUMEN SUDAH DIGUNAKAN!
              </strong>
              <p style={{ marginTop: '0.15rem' }}>
                Kode <code className="mono">{activeCode}</code> sudah terdaftar pada dokumen:{' '}
                <strong>"{conflictingDoc?.title}"</strong>.
                <br />
                Sesuai aturan NBE:{' '}
                <em>"1 kode surat hanya berlaku untuk 1 dokumen saja, tidak boleh lebih."</em>{' '}
                Silakan naikkan nomor urut atau sesuaikan parameter penerbitan.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Manual Override Editor Panel */}
      {isManualOverride && (
        <div
          className="glass-card animate-fade-in"
          style={{
            padding: '1.5rem',
            marginBottom: '2rem',
            border: '1px solid var(--warning)',
            background: 'rgba(245, 158, 11, 0.05)',
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              marginBottom: '1rem',
              color: 'var(--warning)',
            }}
          >
            <Unlock size={20} />
            <h3 style={{ fontSize: '1.05rem', fontWeight: 700 }}>
              Panel Akses Ubah Kode Dokumen (Untuk Dokumen Pra-Sistem / Backdating)
            </h3>
          </div>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1.25rem' }}>
            Anda dapat mengubah langsung teks kode atau mengatur nomor urut dan tanggal penerbitan
            lampau untuk mengarsipkan dokumen yang sudah terbit sebelum sistem ini hadir.
          </p>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
              gap: '1rem',
            }}
          >
            <div className="form-group">
              <label className="form-label">Teks Kode Dokumen Langsung</label>
              <input
                type="text"
                value={manualCode}
                onChange={(e) => setManualCode(e.target.value.toUpperCase())}
                placeholder="0001-SOP-ENG-CTO-IX-2026"
                className="form-input mono"
              />
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                Format: 0000-XXX-YYY-OOO-BLN-THN
              </span>
            </div>

            <div className="form-group">
              <label className="form-label">Nomor Urut Manual</label>
              <input
                type="number"
                min="1"
                value={customSequence}
                onChange={(e) => {
                  const val = e.target.value ? parseInt(e.target.value, 10) : '';
                  setCustomSequence(val);
                  if (val !== '') {
                    setManualCode(
                      generateDocumentCode(
                        val,
                        selectedType,
                        selectedDivision,
                        selectedApprover,
                        monthNumber,
                        year
                      )
                    );
                  }
                }}
                className="form-input mono"
                placeholder="Contoh: 15"
              />
            </div>

            <div className="form-group">
              <label className="form-label">Catatan Dokumen Lampau (Legacy)</label>
              <input
                type="text"
                value={legacyNotes}
                onChange={(e) => setLegacyNotes(e.target.value)}
                placeholder="Contoh: Dokumen fisik lama tahun 2024"
                className="form-input"
              />
            </div>
          </div>
        </div>
      )}

      {/* Main Multi-Step Generator Form */}
      <form onSubmit={handleSubmit}>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
            gap: '1.5rem',
            marginBottom: '2rem',
          }}
        >
          {/* STEP 1: Pilih Kategori Surat (Document Type code) */}
          <div className="glass-card" style={{ padding: '1.5rem' }}>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                marginBottom: '1rem',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem' }}>
                <div
                  style={{
                    width: '28px',
                    height: '28px',
                    borderRadius: '50%',
                    background: 'var(--primary)',
                    color: '#000',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 800,
                    fontSize: '0.85rem',
                  }}
                >
                  1
                </div>
                <h2 style={{ fontSize: '1.05rem', fontWeight: 700 }}>
                  Pilih Kategori Surat (Document Type)
                </h2>
              </div>
              {onNavigateToMasterCategories && (
                <button
                  type="button"
                  onClick={onNavigateToMasterCategories}
                  className="btn btn-ghost btn-sm"
                  style={{ fontSize: '0.72rem', padding: '0.2rem 0.5rem', color: 'var(--primary)' }}
                >
                  + Tambah
                </button>
              )}
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {docTypes.map((dt) => (
                <div
                  key={dt.code}
                  onClick={() => setSelectedType(dt.code)}
                  style={{
                    padding: '0.85rem 1rem',
                    borderRadius: 'var(--radius-md)',
                    border:
                      selectedType === dt.code
                        ? '1.5px solid var(--primary)'
                        : '1px solid var(--border-subtle)',
                    background:
                      selectedType === dt.code
                        ? 'var(--primary-glow)'
                        : 'var(--bg-secondary)',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'flex-start',
                    justifyContent: 'space-between',
                    gap: '0.5rem',
                  }}
                >
                  <div>
                    <div style={{ fontWeight: 700, fontSize: '0.9rem' }}>
                      {dt.label}
                    </div>
                    <div
                      style={{
                        fontSize: '0.78rem',
                        color: 'var(--text-secondary)',
                        marginTop: '0.15rem',
                      }}
                    >
                      {dt.description}
                    </div>
                  </div>
                  <span
                    className="badge badge-purple mono"
                    style={{ fontSize: '0.8rem', padding: '0.2rem 0.5rem' }}
                  >
                    {dt.code}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* STEP 2: Pilih Penerbit Surat (Division code) */}
          <div className="glass-card" style={{ padding: '1.5rem' }}>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                marginBottom: '1rem',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem' }}>
                <div
                  style={{
                    width: '28px',
                    height: '28px',
                    borderRadius: '50%',
                    background: 'var(--accent-blue)',
                    color: '#fff',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 800,
                    fontSize: '0.85rem',
                  }}
                >
                  2
                </div>
                <h2 style={{ fontSize: '1.05rem', fontWeight: 700 }}>
                  Pilih Penerbit Surat (Division)
                </h2>
              </div>
              {onNavigateToMasterCategories && (
                <button
                  type="button"
                  onClick={onNavigateToMasterCategories}
                  className="btn btn-ghost btn-sm"
                  style={{ fontSize: '0.72rem', padding: '0.2rem 0.5rem', color: '#38bdf8' }}
                >
                  + Tambah
                </button>
              )}
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {divs.map((div) => (
                <div
                  key={div.code}
                  onClick={() => setSelectedDivision(div.code)}
                  style={{
                    padding: '0.85rem 1rem',
                    borderRadius: 'var(--radius-md)',
                    border:
                      selectedDivision === div.code
                        ? '1.5px solid var(--accent-blue)'
                        : '1px solid var(--border-subtle)',
                    background:
                      selectedDivision === div.code
                        ? 'rgba(2, 132, 199, 0.15)'
                        : 'var(--bg-secondary)',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'flex-start',
                    justifyContent: 'space-between',
                    gap: '0.5rem',
                  }}
                >
                  <div>
                    <div style={{ fontWeight: 700, fontSize: '0.9rem' }}>
                      {div.label}
                    </div>
                    <div
                      style={{
                        fontSize: '0.78rem',
                        color: 'var(--text-secondary)',
                        marginTop: '0.15rem',
                      }}
                    >
                      {div.description}
                    </div>
                  </div>
                  <span
                    className="badge badge-blue mono"
                    style={{ fontSize: '0.8rem', padding: '0.2rem 0.5rem' }}
                  >
                    {div.code}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* STEP 3: Orang Yang Menyetujui (Approving Authority code) */}
          <div className="glass-card" style={{ padding: '1.5rem' }}>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                marginBottom: '1rem',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem' }}>
                <div
                  style={{
                    width: '28px',
                    height: '28px',
                    borderRadius: '50%',
                    background: 'var(--warning)',
                    color: '#000',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 800,
                    fontSize: '0.85rem',
                  }}
                >
                  3
                </div>
                <h2 style={{ fontSize: '1.05rem', fontWeight: 700 }}>
                  Orang Yang Menyetujui (Approver)
                </h2>
              </div>
              {onNavigateToMasterCategories && (
                <button
                  type="button"
                  onClick={onNavigateToMasterCategories}
                  className="btn btn-ghost btn-sm"
                  style={{ fontSize: '0.72rem', padding: '0.2rem 0.5rem', color: '#f59e0b' }}
                >
                  + Tambah
                </button>
              )}
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {apprvs.map((app) => (
                <div
                  key={app.code}
                  onClick={() => setSelectedApprover(app.code)}
                  style={{
                    padding: '0.75rem 1rem',
                    borderRadius: 'var(--radius-md)',
                    border:
                      selectedApprover === app.code
                        ? '1.5px solid var(--warning)'
                        : '1px solid var(--border-subtle)',
                    background:
                      selectedApprover === app.code
                        ? 'var(--warning-bg)'
                        : 'var(--bg-secondary)',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: '0.5rem',
                  }}
                >
                  <div>
                    <div style={{ fontWeight: 700, fontSize: '0.88rem' }}>
                      {app.label}
                    </div>
                    <div
                      style={{
                        fontSize: '0.75rem',
                        color: 'var(--text-secondary)',
                      }}
                    >
                      {app.description}
                    </div>
                  </div>
                  <span
                    className="badge badge-warning mono"
                    style={{ fontSize: '0.8rem', padding: '0.2rem 0.5rem' }}
                  >
                    {app.code}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* STEP 4: Metadata Dokumen, Upload & Google Drive */}
        <div className="glass-card" style={{ padding: '1.75rem', marginBottom: '2rem' }}>
          <h2
            style={{
              fontSize: '1.15rem',
              fontWeight: 700,
              marginBottom: '1.25rem',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
            }}
          >
            <FileText size={20} color="var(--primary)" />
            Detail & Data Dokumen
          </h2>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
              gap: '1.25rem',
            }}
          >
            {/* Judul Dokumen */}
            <div className="form-group" style={{ gridColumn: 'span 2' }}>
              <label className="form-label">
                Judul Dokumen / Nama Prosedur <span style={{ color: 'var(--danger)' }}>*</span>
              </label>
              <input
                type="text"
                required
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Contoh: DOCUMENTS AND RECORDS CONTROL PROCEDURE"
                className="form-input"
              />
            </div>

            {/* Tanggal Terbit */}
            <div className="form-group">
              <label className="form-label">Tanggal Penerbitan</label>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <input
                  type="date"
                  value={issueDate}
                  onChange={handleDateChange}
                  className="form-input"
                />
              </div>
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                Bulan: {getRomanMonth(monthNumber)} | Tahun: {year}
              </span>
            </div>

            {/* Dibuat Oleh */}
            <div className="form-group">
              <label className="form-label">
                Dibuat Oleh (Created By) <span style={{ color: 'var(--danger)' }}>*</span>
              </label>
              <input
                type="text"
                required
                value={createdBy}
                onChange={(e) => setCreatedBy(e.target.value)}
                placeholder="Contoh: Abdul Q / Staff Name"
                className="form-input"
              />
            </div>

            {/* Diverifikasi Oleh */}
            <div className="form-group">
              <label className="form-label">Diverifikasi Oleh (Verified By)</label>
              <input
                type="text"
                value={verifiedBy}
                onChange={(e) => setVerifiedBy(e.target.value)}
                placeholder="Contoh: Management Representative (MR)"
                className="form-input"
              />
            </div>

            {/* Disetujui Oleh */}
            <div className="form-group">
              <label className="form-label">Disetujui Oleh (Approved By)</label>
              <input
                type="text"
                value={approvedBy}
                onChange={(e) => setApprovedBy(e.target.value)}
                placeholder="Contoh: President Director (CEO)"
                className="form-input"
              />
            </div>

            {/* Status Dokumen */}
            <div className="form-group">
              <label className="form-label">Status Dokumen</label>
              <select
                value={status}
                onChange={(e) => setStatus(e.target.value as DocumentStatus)}
                className="form-select"
              >
                <option value="Published">Published (Diterbitkan & Berlaku)</option>
                <option value="Approved">Approved (Telah Disetujui)</option>
                <option value="In Review">In Review (Sedang Direview)</option>
                <option value="Draft">Draft (Konsep)</option>
                <option value="Archived">Archived (Diarsipkan / Digantikan)</option>
              </select>
            </div>

            {/* Revisi Index */}
            <div className="form-group">
              <label className="form-label">Nomor Revisi</label>
              <input
                type="number"
                min="0"
                value={revision}
                onChange={(e) => setRevision(parseInt(e.target.value, 10) || 0)}
                className="form-input mono"
              />
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                Revisi 0 adalah penerbitan perdana (Initial Issue)
              </span>
            </div>

            {/* Deskripsi / Lingkup */}
            <div className="form-group" style={{ gridColumn: 'span 2' }}>
              <label className="form-label">Deskripsi / Ruang Lingkup Dokumen</label>
              <textarea
                rows={2}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Keterangan singkat maksud dan tujuan dokumen..."
                className="form-textarea"
              />
            </div>
          </div>

          {/* Upload Dokumen & Google Drive Section */}
          <div
            style={{
              marginTop: '1.5rem',
              paddingTop: '1.5rem',
              borderTop: '1px solid var(--border-subtle)',
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
              gap: '1.5rem',
            }}
          >
            {/* Tombol Upload Dokumen */}
            <div>
              <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                <Upload size={14} color="var(--primary)" />
                Upload File Dokumen (PDF, Word, Excel)
              </label>

              <div
                style={{
                  border: '2px dashed var(--border-accent)',
                  borderRadius: 'var(--radius-md)',
                  padding: '1.25rem',
                  textAlign: 'center',
                  background: 'var(--bg-secondary)',
                  cursor: 'pointer',
                  position: 'relative',
                }}
              >
                <input
                  type="file"
                  accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg"
                  onChange={handleFileChange}
                  style={{
                    position: 'absolute',
                    top: 0,
                    left: 0,
                    width: '100%',
                    height: '100%',
                    opacity: 0,
                    cursor: 'pointer',
                  }}
                />

                {uploadedFile ? (
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem' }}>
                    <FileCheck size={28} color="var(--primary)" />
                    <div style={{ textAlign: 'left' }}>
                      <div style={{ fontWeight: 600, fontSize: '0.875rem' }}>
                        {uploadedFile.name}
                      </div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                        {(uploadedFile.size / 1024).toFixed(1)} KB • {uploadedFile.type || 'Dokumen'}
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        setUploadedFile(null);
                        setBotUploadSuccess(null);
                        setBotUploadError(null);
                      }}
                      className="btn btn-ghost btn-sm"
                      style={{ padding: '0.2rem', color: 'var(--danger)' }}
                    >
                      <X size={16} />
                    </button>
                  </div>
                ) : (
                  <div>
                    <Upload size={24} color="var(--text-muted)" style={{ margin: '0 auto 0.5rem auto' }} />
                    <p style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-main)' }}>
                      Klik atau Seret file dokumen ke sini
                    </p>
                    <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.25rem' }}>
                      Mendukung PDF, Word (.docx), Excel, gambar
                    </p>
                  </div>
                )}
              </div>

              {/* Tombol Upload ke Google Drive via Bot */}
              {uploadedFile && (
                <div style={{ marginTop: '0.75rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                  <button
                    type="button"
                    onClick={handleUploadViaBot}
                    disabled={isBotUploading}
                    className="btn btn-sm"
                    style={{
                      background: 'linear-gradient(90deg, #0284c7 0%, #0369a1 100%)',
                      color: '#ffffff',
                      border: 'none',
                      fontWeight: 600,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      gap: '0.5rem',
                      padding: '0.65rem 1rem',
                      borderRadius: 'var(--radius-md)',
                      boxShadow: '0 2px 8px rgba(2, 132, 199, 0.25)',
                      cursor: isBotUploading ? 'wait' : 'pointer',
                    }}
                  >
                    {isBotUploading ? (
                      <>
                        <Loader2 size={16} className="animate-spin" />
                        <span>Bot sedang mengunggah dokumen ke Google Drive...</span>
                      </>
                    ) : (
                      <>
                        <Bot size={16} />
                        <span>🤖 Upload ke Google Drive via Bot</span>
                      </>
                    )}
                  </button>

                  {botUploadSuccess && (
                    <div
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        padding: '0.6rem 0.85rem',
                        borderRadius: 'var(--radius-md)',
                        background: 'rgba(16, 185, 129, 0.1)',
                        border: '1px solid var(--success)',
                        color: 'var(--success)',
                        fontSize: '0.8rem',
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                        <CheckCircle2 size={16} />
                        <span>Berhasil diunggah oleh Bot ke Google Drive!</span>
                      </div>
                      <a
                        href={botUploadSuccess.viewUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{
                          color: '#38bdf8',
                          fontWeight: 600,
                          display: 'flex',
                          alignItems: 'center',
                          gap: '0.25rem',
                          textDecoration: 'underline',
                        }}
                      >
                        <ExternalLink size={12} /> Buka di Drive
                      </a>
                    </div>
                  )}

                  {botUploadError && (
                    <div
                      style={{
                        padding: '0.6rem 0.85rem',
                        borderRadius: 'var(--radius-md)',
                        background: 'rgba(239, 68, 68, 0.1)',
                        border: '1px solid var(--danger)',
                        color: '#fca5a5',
                        fontSize: '0.8rem',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        gap: '0.5rem',
                      }}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                        <AlertCircle size={15} />
                        <span>{botUploadError}</span>
                      </div>
                      {onOpenDriveSettings && (
                        <button
                          type="button"
                          onClick={onOpenDriveSettings}
                          className="btn btn-ghost btn-sm"
                          style={{ fontSize: '0.72rem', padding: '0.2rem 0.5rem', color: '#38bdf8' }}
                        >
                          Pasang Bot
                        </button>
                      )}
                    </div>
                  )}
                </div>
              )}
            </div>

            {/* Integrasi Database Google Drive */}
            <div>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  marginBottom: '0.5rem',
                }}
              >
                <label className="form-label" style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                  <HardDrive size={14} color="#38bdf8" />
                  Database Google Drive (Link Arsip Cloud)
                </label>
                <a
                  href={driveSettings.folderUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn btn-ghost btn-sm"
                  style={{ fontSize: '0.72rem', padding: '0.2rem 0.5rem', color: '#38bdf8' }}
                >
                  <ExternalLink size={12} /> Buka Folder Drive
                </a>
              </div>

              <input
                type="url"
                value={googleDriveLink}
                onChange={(e) => setGoogleDriveLink(e.target.value)}
                placeholder="https://drive.google.com/file/d/..."
                className="form-input"
              />
              <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.4rem' }}>
                Tempel link Google Drive dokumen agar seluruh tim dapat menelusuri kembali arsip dokumen lama kapan saja.
              </p>
            </div>
          </div>
        </div>

        {/* Error message */}
        {errorMsg && (
          <div
            style={{
              padding: '0.85rem 1rem',
              borderRadius: 'var(--radius-md)',
              background: 'var(--danger-bg)',
              border: '1px solid var(--danger)',
              color: '#fca5a5',
              marginBottom: '1.5rem',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              fontSize: '0.875rem',
            }}
          >
            <AlertTriangle size={18} color="var(--danger)" />
            <span>{errorMsg}</span>
          </div>
        )}

        {/* Action Submit */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '1rem' }}>
          <button
            type="submit"
            disabled={isSubmitting || duplicate}
            className="btn btn-primary btn-lg"
            style={{
              opacity: duplicate ? 0.6 : 1,
              cursor: duplicate ? 'not-allowed' : 'pointer',
              minWidth: '220px',
            }}
          >
            <CheckCircle2 size={20} />
            <span>{isSubmitting ? 'Menyimpan...' : 'Daftarkan & Simpan Dokumen'}</span>
          </button>
        </div>
      </form>
    </div>
  );
};
